// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfxvjuymdufazwthlmhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmeHZqdXltZHVmYXp3dGhsbWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTY0MjcsImV4cCI6MjA3NDA3MjQyN30.xMCBEted6faxb8la3m1URF2nESfTSixoZ0Cb5_lM4cI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});