// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrjdsspxjtkfoerapkfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yamRzc3B4anRrZm9lcmFwa2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NjQwNjMsImV4cCI6MjA3ODA0MDA2M30.2z23PxYcEqlZmDiZj_xSYRVi-hFqraIXnG3gM1Nup84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});